package com.yum.ph.messaging.ws;

import javax.jws.WebParam;

/**
 * This class was generated by Apache CXF 2.5.1
 * 2017-04-12T15:12:45.653-05:00
 * Generated source version: 2.5.1
 * 
 */
public class PHStoreMessageDispatcherService implements PHStoreMessageDispatcher {

	public PHDispatchResponse dispatchMessage(@WebParam(partName = "body", name = "PHStoreMessage", targetNamespace = "http://ws.yum.com/phmf/PHStoreMessageDispatcher") PHStoreMessage body)
	{
		String payload = body.getPayload();
		String type = body.getType();
		
		System.out.println(" Payload "+payload+" and type "+type);
		PHDispatchResponse response = new PHDispatchResponse();
		response.setDescription("OK");
		return response;
	}
}
